DROP TABLE IF EXISTS role_authority CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS oauth_access_token CASCADE;
DROP TABLE IF EXISTS oauth_refresh_token CASCADE;

DROP TABLE IF EXISTS bundle CASCADE;
DROP TABLE IF EXISTS subscription CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS client CASCADE;
